### ISSUE TITLE
App failed to build : Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by bdaykid** [dns-technologies/mlkit_scanner#4] opened 2022-08-04 08:01 UTC
Hi, thank you for the library. I already follow the steps and refer to this repo for instructions. But when I try to run the app an error occurred : 

e: /Users/me/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/mlkit_scanner-0.3.1/android/src/main/kotlin/com/dns_technologies/mlkit_scanner/analyzer/MlSingleBarcodeAnalyzer.kt: (89, 28): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlkit_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

flutter -v doctor output : 

[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.2 20G314 darwin-x64, locale en-MY)
    • Flutter version 3.0.5 at /Users/me/FlutterProjects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /...
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /...
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at ...
    • Flutter extension version 3.46.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by skrjt** [comment] 2022-08-07 23:36
Hi, @bdaykid, thanks for creating issue!
I see that the problem is in the null check. I create PR, which will most likely solve the compilation problem.
To be completely sure of this, can you attach the kotlin (just in case) and gradle versions? 

In our example we use kotlin 1.6.10 and gradle 6.7.1 and everything compiles correctly.

**Comment by bdaykid** [comment] 2022-08-08 00:36
Hi @skrjt , thank you for your response. my project's kotlin version is also 1.6.10 and gradle as below : 

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

**Comment by grebennikovlmax** [comment] 2022-08-08 23:39
Issue has fixed in version 0.3.2.

**Closed by grebennikovlmax** 2022-08-08 23:39 UTC

**Comment by bdaykid** [comment] 2022-08-10 02:40
> 

thank you! Will try ASAP

**Comment by skrjt** [comment] 2022-08-14 11:31
It looks as if the old versions of gradle are worse smartcasting in non-nullable types. This is still our bug, I would like the plugin to be built on older versions of gradle.
I caught the same error, it seems https://github.com/dns-technologies/mlkit_scanner/pull/6 should help.
